### ISSUE TITLE
bug: Clicking on the whatsapp notificaiton from the notification centre does not go to the whatsapp tab

### ISSUE THREAD

**Issue by cotfas** [atomery/singlebox#282]
SB 3.7.0
Mac 10.15.5

Clicking on the whatsapp notificaiton from the notification centre does not go to the whatsapp tab.

App used:

![image](https://user-images.githubusercontent.com/3340367/83324008-f3477100-a26a-11ea-989e-4870a371dd4c.png)

**Comment by quanglam2807** [comment]
Thanks for reporting this! This bug is critical and I'll try to fix it ASAP.

**Comment by quanglam2807** [comment]
Resolve #288
